'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { AlertTriangle, Camera, CheckCircle2, ChevronRight, CircleUserRound, FileVideo, MapPin, Menu, Plus, Search, Sparkles, ThumbsUp, X, ZoomIn, ZoomOut } from 'lucide-react'
import { IntroScene } from '@/components/intro-scene'
import { AuthPanel } from '@/components/auth-panel'
import { authClient } from '@/lib/auth-client'

type Media = { name: string; type: string; url: string }
type Report = { id: string; reportNo: string; title: string; category: string; description: string; location: string; latitude: number; longitude: number; status: string; severity: string; isAnonymous: boolean; upvotes: number; media: Media[]; createdAt: string }

const categories = ['Waste', 'Lighting', 'Water', 'Roads', 'Safety']
const emptyForm = { title: '', category: 'Waste', description: '', location: '', severity: 'Medium', isAnonymous: false, media: [] as Media[] }

export default function Page() {
  const [reports, setReports] = useState<Report[]>([])
  const [selected, setSelected] = useState<Report | null>(null)
  const [showForm, setShowForm] = useState(false)
  const [query, setQuery] = useState('')
  const [profile, setProfile] = useState(false)
  const [showIntro, setShowIntro] = useState(true)
  const [authOpen, setAuthOpen] = useState(false)
  const [signedIn, setSignedIn] = useState(false)
  const [notice, setNotice] = useState('')
  const [loading, setLoading] = useState(true)
  const [form, setForm] = useState(emptyForm)
  const [zoom, setZoom] = useState(1)
  const [pan, setPan] = useState({ x: 0, y: 0 })
  const drag = useRef({ active: false, x: 0, y: 0 })

  useEffect(() => { fetch('/api/reports').then(r => r.ok ? r.json() : []).then(data => { const rows = Array.isArray(data) ? data : []; setReports(rows); setSelected(rows[0] ?? null) }).catch(() => setNotice('Connect the database to load live reports.')).finally(() => setLoading(false)); authClient.getSession().then(({ data }) => setSignedIn(Boolean(data?.user))).catch(() => setSignedIn(false)) }, [])
  const openReport = () => { if (!signedIn) setAuthOpen(true); else setShowForm(true) }
  const filtered = useMemo(() => reports.filter(r => `${r.title} ${r.category} ${r.location}`.toLowerCase().includes(query.toLowerCase())), [reports, query])
  const submit = async (e: React.FormEvent) => { e.preventDefault(); const payload = { ...form, latitude: 50, longitude: 50 }; const res = await fetch('/api/reports', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!res.ok) { setNotice('Could not save this report. Check the database connection.'); return }; const created = await res.json(); setReports(r => [created, ...r]); setSelected(created); setShowForm(false); setNotice(`Report ${created.reportNo} is now live.`); setForm(emptyForm); setTimeout(() => setNotice(''), 4000) }
  const onFiles = (files: FileList | null) => { if (!files) return; setForm(f => ({ ...f, media: [...f.media, ...Array.from(files).map(file => ({ name: file.name, type: file.type, url: URL.createObjectURL(file) }))] })) }
  const beginDrag = (e: React.PointerEvent) => { drag.current = { active: true, x: e.clientX - pan.x, y: e.clientY - pan.y }; (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId) }
  const moveDrag = (e: React.PointerEvent) => { if (drag.current.active) setPan({ x: e.clientX - drag.current.x, y: e.clientY - drag.current.y }) }
  const endDrag = () => { drag.current.active = false }
  const changeZoom = (delta: number) => setZoom(z => Math.min(2.1, Math.max(.75, +(z + delta).toFixed(2))))

  if (showIntro) return <IntroScene onEnter={() => setShowIntro(false)} />

  return <main className="min-h-screen bg-background text-foreground"><header className="flex items-center justify-between border-b border-border/70 bg-card/85 px-5 py-4 backdrop-blur md:px-10"><div className="flex items-center gap-3"><div className="brand-mark"><MapPin /></div><div><div className="text-lg font-black tracking-tight">Community<span className="text-primary">Connector</span></div><div className="hidden text-[10px] font-bold uppercase tracking-[.24em] text-muted-foreground sm:block">Make your street heard</div></div></div><nav className="hidden items-center gap-7 text-sm font-semibold text-muted-foreground md:flex"><a href="#map" className="text-foreground">Explore map</a><a href="#activity">Community activity</a></nav><div className="flex items-center gap-2"><button onClick={() => setProfile(true)} className="profile-button"><CircleUserRound /> <span className="hidden sm:inline">My profile</span></button><button onClick={() => openReport()} className="report-button"><Plus /> Report issue</button><button className="icon-button md:hidden"><Menu /></button></div></header>
    <section className="hero-shell"><div><div className="eyebrow"><Sparkles /> Civic tech, powered by people</div><h1>Spot it.<br /><span>Share it.</span><br />Solve it together.</h1><p>One clear channel for everyday issues in your neighborhood. Every marker below comes from a real report in your connected database.</p><button onClick={() => openReport()} className="hero-cta">Create a report <ChevronRight /></button></div><div className="hero-stats"><div><strong>{reports.length}</strong><span>live reports</span></div><div><strong>{reports.filter(r => r.status === 'Resolved').length}</strong><span>resolved</span></div><div><strong>{reports.filter(r => r.status === 'In Progress').length}</strong><span>in progress</span></div></div></section>
    <section className="workspace" id="map"><div className="workspace-top"><div><div className="section-kicker">LIVE COMMUNITY MAP</div><h2>Issues near you</h2></div><div className="search-box"><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search reports" aria-label="Search reports" /></div></div><div className="map-layout"><div className="map-canvas" onPointerDown={beginDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag}><div className="map-viewport" style={{ transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})` }}><div className="map-road road-a" /><div className="map-road road-b" /><div className="map-road road-c" /><div className="map-park">COMMUNITY<br />GREEN</div><div className="map-label label-a">Cedar Avenue</div><div className="map-label label-b">14th Street</div>{filtered.map(report => <button key={report.id} className={`map-pin ${selected?.id === report.id ? 'active' : ''}`} style={{ left: `${report.longitude}%`, top: `${report.latitude}%` }} onPointerDown={e => e.stopPropagation()} onClick={() => setSelected(report)} aria-label={`Open ${report.title}`}><span>{report.category === 'Waste' ? '♻' : report.category === 'Water' ? '≈' : report.category === 'Lighting' ? '✦' : '!'}</span></button>)}</div><div className="map-controls"><button onClick={() => changeZoom(.15)} aria-label="Zoom in"><ZoomIn /></button><button onClick={() => changeZoom(-.15)} aria-label="Zoom out"><ZoomOut /></button><button onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }) }} aria-label="Reset map">Reset</button></div><div className="map-hint">Drag to explore · click a marker for details</div></div>
      <aside className="issue-panel"><div className="panel-heading"><span>{filtered.length} {filtered.length === 1 ? 'report' : 'reports'}</span><span className="live-dot">LIVE</span></div>{loading ? <div className="empty-state">Loading live reports…</div> : filtered.length === 0 ? <div className="empty-state"><MapPin /><strong>No reports yet</strong><span>Be the first person to document an issue in your community.</span><button onClick={() => openReport()} className="text-button">Create a report</button></div> : <div className="issue-list">{filtered.map(report => <button key={report.id} onClick={() => setSelected(report)} className={`issue-card ${selected?.id === report.id ? 'selected' : ''}`}><div className="issue-card-top"><span className={`category-icon ${report.category.toLowerCase()}`}><AlertTriangle /></span><span className="status-pill">{report.status}</span></div><strong>{report.title}</strong><small>{report.location} · {report.reportNo}</small><div className="issue-card-bottom"><span>{report.severity} severity</span><span><ThumbsUp /> {report.upvotes}</span></div></button>)}</div>}</aside></div></section>
    {selected && <section className="detail-strip"><div><div className="section-kicker">SELECTED REPORT · {selected.reportNo}</div><h2>{selected.title}</h2><p>{selected.description}</p><div className="detail-meta"><span><MapPin /> {selected.location}</span><span className={`status-pill ${selected.status.toLowerCase().replaceAll(' ', '-')}`}>{selected.status}</span><span><ThumbsUp /> {selected.upvotes} neighbors</span></div></div><button onClick={() => setSelected(null)} aria-label="Close details" className="close-button"><X /></button></section>}
    <section className="activity" id="activity"><div><div className="section-kicker">THE REAL PULSE</div><h2>Community activity</h2><p>Metrics are derived only from reports currently stored in the database.</p></div><div className="activity-grid"><div><strong>{reports.length}</strong><span>Total reports</span></div><div><strong>{reports.filter(r => r.status === 'Reported').length}</strong><span>Awaiting review</span></div><div><strong>{reports.reduce((sum, r) => sum + r.upvotes, 0)}</strong><span>Total upvotes</span></div></div></section>
    {notice && <div className="notice">{notice}</div>}{showForm && <div className="modal-backdrop" onClick={() => setShowForm(false)}><form className="report-modal" onClick={e => e.stopPropagation()} onSubmit={submit}><div className="modal-header"><div><div className="section-kicker">NEW COMMUNITY REPORT</div><h2>Document an issue</h2></div><button type="button" onClick={() => setShowForm(false)} className="close-button"><X /></button></div><label>Issue title<input required minLength={3} value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="What needs attention?" /></label><div className="form-grid"><label>Category<select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>{categories.map(c => <option key={c}>{c}</option>)}</select></label><label>Severity<select value={form.severity} onChange={e => setForm({ ...form, severity: e.target.value })}><option>Low</option><option>Medium</option><option>High</option></select></label></div><label>Location<input required minLength={2} value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} placeholder="Street, landmark, or neighborhood" /></label><label>Description<textarea required minLength={10} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="Tell neighbors what is happening…" /></label><label className="upload-zone"><Camera /> Add photo or <FileVideo /> video<input type="file" accept="image/*,video/*" multiple onChange={e => onFiles(e.target.files)} />{form.media.length > 0 && <span>{form.media.length} file(s) ready</span>}</label><label className="check-row"><input type="checkbox" checked={form.isAnonymous} onChange={e => setForm({ ...form, isAnonymous: e.target.checked })} /> Submit anonymously</label><button className="submit-report" type="submit">Publish report <ChevronRight /></button></form></div>}{profile && <div className="modal-backdrop" onClick={() => setProfile(false)}><div className="profile-modal" onClick={e => e.stopPropagation()}><button onClick={() => setProfile(false)} className="close-button"><X /></button><div className="profile-avatar">CC</div><div className="section-kicker">CITIZEN PROFILE</div><h2>Your community profile</h2><p>Edit your profile in V1 by connecting it to your preferred authentication provider. Your report history will appear here as you publish issues.</p><div className="profile-facts"><span>{reports.length} reports</span><span>{reports.reduce((sum, r) => sum + r.upvotes, 0)} impact points</span></div></div></div>}{authOpen && <AuthPanel onClose={() => setAuthOpen(false)} onSuccess={() => { setSignedIn(true); setAuthOpen(false); setShowForm(true) }} />}</main>
}
